POST http://localhost:1234/signup
Content-Type: application/json

{
    "username":"razzaksr",
    "password":"mohamed",
    "fullname":"Razak Mohamed S",
    "accountno":876587656789,
    "accountbal":245.6
}

###

POST http://localhost:1234/login
Content-Type: application/json

{
    "username":"razzaksr",
    "password":"mohamed"
}

###

POST http://localhost:1234/ben/new
Content-Type: application/json

{
    "beneficiaryaccount":456787653,
    "beneficiaryname":"Dharun",
    "beneficiarymapped":876587656789
}